# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 03:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='quote_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ids', to='first.Quote'),
        ),
    ]
